defmodule SpaceTraders.API.OperationInventory.Operation do
  @moduledoc false
  @enforce_keys [
    :id,
    :method,
    :path,
    :spec_fingerprint,
    :classification,
    :owner,
    :prerequisites,
    :consequences,
    :success_evidence,
    :waits,
    :ambiguity,
    :visibility,
    :pagination
  ]
  defstruct @enforce_keys

  @type t() :: %__MODULE__{}
end

defmodule SpaceTraders.API.OperationInventory do
  @moduledoc """
  Generated inventory of every operation in the pinned SpaceTraders API.

  Regenerate with `mix space_traders.gen.operations`; edit operation governance
  metadata in that task rather than editing this file directly.
  """

  alias SpaceTraders.API.OperationInventory.Operation

  @operations [
    %Operation{
      id: "accept-contract",
      method: :post,
      path: "/my/contracts/{contractId}/accept",
      spec_fingerprint: "ccd706786d5a477d1fe10a47f8cea08a51a8e319a917c04e85983c7f11fb8374",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["available Contract before acceptance deadline"],
      consequences: ["accepts Contract and may pay acceptance credits"],
      success_evidence: ["Agent and Contract response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Contract state", "Agent credits"]},
      visibility: :agent_private,
      pagination: :none
    },
    %Operation{
      id: "create-chart",
      method: :post,
      path: "/my/ships/{shipSymbol}/chart",
      spec_fingerprint: "a6f16abb7dfe5887b2a5ce5d1612473f5dc2038b31c2ee006849ed21bd982aea",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["uncharted current Waypoint"],
      consequences: ["charts current Waypoint and may add credits"],
      success_evidence: ["Chart, Waypoint, and Agent response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Waypoint Chart", "Agent credits"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "create-ship-ship-scan",
      method: :post,
      path: "/my/ships/{shipSymbol}/scan/ships",
      spec_fingerprint: "203e97888437da554940c3657a6d50ae5c0cae8253304383076b22e21cdf3b85",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["sensor mount", "eligible Ship"],
      consequences: ["observes nearby Ships"],
      success_evidence: ["scanned Ships and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship Cooldown", "Bounded Unknown scan results"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "create-ship-system-scan",
      method: :post,
      path: "/my/ships/{shipSymbol}/scan/systems",
      spec_fingerprint: "68ecfe8f97b7b79febea9a9903055216e2565917f66499e2c6277cd435b9af17",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["sensor mount", "eligible Ship"],
      consequences: ["observes nearby Systems"],
      success_evidence: ["scanned Systems and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship Cooldown", "Bounded Unknown scan results"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "create-ship-waypoint-scan",
      method: :post,
      path: "/my/ships/{shipSymbol}/scan/waypoints",
      spec_fingerprint: "eff9359645c17b7cf322ee9bbd2bf88b78560e96fc522e27091d54b6714bbb43",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["sensor mount", "eligible Ship"],
      consequences: ["observes nearby Waypoints"],
      success_evidence: ["scanned Waypoints and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship Cooldown", "Bounded Unknown scan results"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "create-survey",
      method: :post,
      path: "/my/ships/{shipSymbol}/survey",
      spec_fingerprint: "e6e9b87722898e9b42b0fde03bb42b8c712020e4da380408e679d86bbbd8a5b3",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["survey mount", "surveyable Waypoint"],
      consequences: ["creates Surveys"],
      success_evidence: ["Surveys and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship Cooldown", "Bounded Unknown Surveys"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "deliver-contract",
      method: :post,
      path: "/my/contracts/{contractId}/deliver",
      spec_fingerprint: "8ebfab7c92b54e147652eeaa42eb3aa14eb6e0f32775dc49ae4e0abdb53366ad",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship at delivery Waypoint with required Cargo"],
      consequences: ["removes Cargo and advances Contract delivery"],
      success_evidence: ["Cargo and Contract response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Contract delivery", "Ship Cargo"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "dock-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/dock",
      spec_fingerprint: "3c42e8f890cd0dca26b0c57e16d17da768431fd8934d59c5931827483f6e5e99",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["orbiting Ship"],
      consequences: ["changes Ship posture to docked"],
      success_evidence: ["Ship nav response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "extract-resources",
      method: :post,
      path: "/my/ships/{shipSymbol}/extract",
      spec_fingerprint: "d043a44116f86ce89321a987b35103993cb57beb771cb9e59b400d8467937d4d",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["extraction mount", "extractable Waypoint", "Cargo capacity"],
      consequences: ["adds extracted Cargo"],
      success_evidence: ["Extraction, Cargo, and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "extract-resources-with-survey",
      method: :post,
      path: "/my/ships/{shipSymbol}/extract/survey",
      spec_fingerprint: "2b2a66391b1aaa5022755ce88d354bf39dd872a8b112ce293b0903adc57f2dda",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["valid matching Survey", "extraction capability", "Cargo capacity"],
      consequences: ["adds extracted Cargo and may exhaust Survey"],
      success_evidence: ["Extraction, Cargo, events, and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "fulfill-contract",
      method: :post,
      path: "/my/contracts/{contractId}/fulfill",
      spec_fingerprint: "083293a3b7d26dfebada62407424c6168b212969e15e85ff6e8fda253d14e46e",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["accepted Contract with all deliveries complete"],
      consequences: ["fulfills Contract and pays completion credits"],
      success_evidence: ["Agent and Contract response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Contract state", "Agent credits"]},
      visibility: :agent_private,
      pagination: :none
    },
    %Operation{
      id: "get-agent",
      method: :get,
      path: "/agents/{agentSymbol}",
      spec_fingerprint: "babadb3e3fe17e307c988394286481f33f25dcab9ffad3e14e19b464431b7489",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :none
    },
    %Operation{
      id: "get-agents",
      method: :get,
      path: "/agents",
      spec_fingerprint: "877be22d3466d6c06c00dfd778cd2be023f306f05c79156d2daee9665d3aafd1",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :page_limit
    },
    %Operation{
      id: "get-construction",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/construction",
      spec_fingerprint: "4320e38a73456ce68ae23f9a9e7a07aa06e24fe1c9f181cc3e11f89faf3ce23a",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :none
    },
    %Operation{
      id: "get-contract",
      method: :get,
      path: "/my/contracts/{contractId}",
      spec_fingerprint: "db00969e7d1236c50fd3d5b4fef1e861c4234490397706b6e89ba805171c2784",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :agent_private,
      pagination: :none
    },
    %Operation{
      id: "get-contracts",
      method: :get,
      path: "/my/contracts",
      spec_fingerprint: "cb600ab34016560cf32d214351ecf8c6528dd215b498e59119ace93739d42379",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :agent_private,
      pagination: :page_limit
    },
    %Operation{
      id: "get-faction",
      method: :get,
      path: "/factions/{factionSymbol}",
      spec_fingerprint: "4c91e239d9140e7bf6314ea9cfc062c9e5c73d8dff21da934cb667c6bb970517",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :none
    },
    %Operation{
      id: "get-factions",
      method: :get,
      path: "/factions",
      spec_fingerprint: "f9f31a5a15deceb9d6195e07d4fa0df477bbf7213730b651c48fbdc2ec9157a3",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :page_limit
    },
    %Operation{
      id: "get-jump-gate",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/jump-gate",
      spec_fingerprint: "71d4d9f1240819ab291b2fd80279b44333961fd77e5b5294597f9364d4ce5b99",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :none
    },
    %Operation{
      id: "get-market",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/market",
      spec_fingerprint: "4bb0e7b4701752df7d9388761007a3e357a3b67744024c9f78ab7954b90fb8b5",
      classification: :read,
      owner: :evidence,
      prerequisites: [
        "requested Waypoint identifiers",
        "Ship presence for full Listing visibility"
      ],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :location_dependent_listing,
      pagination: :none
    },
    %Operation{
      id: "get-mounts",
      method: :get,
      path: "/my/ships/{shipSymbol}/mounts",
      spec_fingerprint: "206071f60f2e5d015c034694f31dc86f03b3bb161056971773bbc542c4550373",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "get-my-agent",
      method: :get,
      path: "/my/agent",
      spec_fingerprint: "fee065e5ee1e9199b792e92fde9bbfb8780268d53e0ffffe568d0935b40e880f",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :agent_private,
      pagination: :none
    },
    %Operation{
      id: "get-my-ship",
      method: :get,
      path: "/my/ships/{shipSymbol}",
      spec_fingerprint: "f3b827ce9db09a567a1efcbbfe42a53a06267e4c38b60bcaf957567bdd694911",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "get-my-ship-cargo",
      method: :get,
      path: "/my/ships/{shipSymbol}/cargo",
      spec_fingerprint: "88234c86b71df1160a050060dba1720de659e359e909c7861b31a5227dfb4116",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "get-my-ships",
      method: :get,
      path: "/my/ships",
      spec_fingerprint: "cb517e888eb33a9c2e7f077d83ba9492daca4da24377b0dd3172733479c2010c",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :agent_private,
      pagination: :page_limit
    },
    %Operation{
      id: "get-repair-ship",
      method: :get,
      path: "/my/ships/{shipSymbol}/repair",
      spec_fingerprint: "5f8c3a0b051e3eb1cf659cb9fe308170148779632538f6982603f924f673323b",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "get-scrap-ship",
      method: :get,
      path: "/my/ships/{shipSymbol}/scrap",
      spec_fingerprint: "946a7e4a08caa51e9f3241ee6fb7b6bf8bfc0983d1d7e3d93947bf3b190a4449",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "get-ship-cooldown",
      method: :get,
      path: "/my/ships/{shipSymbol}/cooldown",
      spec_fingerprint: "aaa0665e9a8ee882d2e6f0356fe38ad00f2121f67cc8b1e864e39ebe4c432590",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "get-ship-modules",
      method: :get,
      path: "/my/ships/{shipSymbol}/modules",
      spec_fingerprint: "a727971990542937cb6e500250e72b603848f68564f9e4b9a26b8e28202cc86a",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "get-ship-nav",
      method: :get,
      path: "/my/ships/{shipSymbol}/nav",
      spec_fingerprint: "714bdac8016bc56158a601402a5d4689aeaa8c42060e8fd6d6d9278ba645a3b3",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "get-shipyard",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/shipyard",
      spec_fingerprint: "ad15862e736110090fa3fb79a4c050c050746bb2327f2de80089213950056e59",
      classification: :read,
      owner: :evidence,
      prerequisites: [
        "requested Waypoint identifiers",
        "Ship presence for full Listing visibility"
      ],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :location_dependent_listing,
      pagination: :none
    },
    %Operation{
      id: "get-status",
      method: :get,
      path: "/",
      spec_fingerprint: "a20260c6d67e5efd873ce2bfe79fe4aa1ac562c210e72397a6929d120d8bd2cd",
      classification: :read,
      owner: :evidence,
      prerequisites: ["public API availability"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :none
    },
    %Operation{
      id: "get-supply-chain",
      method: :get,
      path: "/market/supply-chain",
      spec_fingerprint: "53f240d6fa5affb06d0b312d86b5ba285bb84cca0e54c210a4e84fa32abca482",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :none
    },
    %Operation{
      id: "get-system",
      method: :get,
      path: "/systems/{systemSymbol}",
      spec_fingerprint: "f9ef82d8f750717d831873a55d8bef01132bcd968d0e2e95c15afa6f21312308",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :none
    },
    %Operation{
      id: "get-system-waypoints",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints",
      spec_fingerprint: "b3fc81263e9199b029758459daccf173feb2dcc9c58920a40e63b3c123bb19aa",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :page_limit
    },
    %Operation{
      id: "get-systems",
      method: :get,
      path: "/systems",
      spec_fingerprint: "e2ff728687b1f4c635318021d815de017101eea5aeabb7ed85bc44070e30f532",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :page_limit
    },
    %Operation{
      id: "get-waypoint",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}",
      spec_fingerprint: "0c00ffe6d70ebb73ffaed372cc198c9c56e992c190873bc0bf515835d2b757fd",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :global_game_state,
      pagination: :none
    },
    %Operation{
      id: "install-mount",
      method: :post,
      path: "/my/ships/{shipSymbol}/mounts/install",
      spec_fingerprint: "b5cb4bade2309314623b45cd1483b8c7d0b2f73703ad4a0341e6be1bd933d46e",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship at capable Shipyard", "mount in Cargo", "Ship capacity"],
      consequences: ["moves mount from Cargo onto Ship and may spend credits"],
      success_evidence: ["mounts, Cargo, Agent, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship Cargo", "Ship Readiness"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "install-ship-module",
      method: :post,
      path: "/my/ships/{shipSymbol}/modules/install",
      spec_fingerprint: "37205f389809f787e49374fd87fdfc2723ed27f1a2a21866428df120f0ce13c8",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship docked at capable Shipyard", "module in Cargo", "Ship capacity"],
      consequences: ["moves module from Cargo onto Ship and may spend credits"],
      success_evidence: ["modules, Cargo, Agent, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Ship Readiness"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "jettison",
      method: :post,
      path: "/my/ships/{shipSymbol}/jettison",
      spec_fingerprint: "9242c6920fbc99f2fe287ed60ab9cf95512e0d6cf5e677ccf12b6341885b53fe",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Cargo units aboard"],
      consequences: ["removes Cargo"],
      success_evidence: ["Cargo response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship Cargo", "Ship Readiness"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "jump-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/jump",
      spec_fingerprint: "a7e519855db3ca4024e8016047f4a7a61add6a60fa2086a46429b02553a13fad",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["connected Jump Gate", "eligible Ship"],
      consequences: ["relocates Ship to the connected System"],
      success_evidence: ["Ship nav, Agent, and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "navigate-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/navigate",
      spec_fingerprint: "0e88cb60e95692fe6228415e4fb490131b1d35279057f6d34380283abd473849",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["reachable destination", "sufficient fuel"],
      consequences: ["starts local transit"],
      success_evidence: ["Ship nav and fuel response"],
      waits: [:transit],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "negotiateContract",
      method: :post,
      path: "/my/ships/{shipSymbol}/negotiate/contract",
      spec_fingerprint: "9dd7c322173a509e7bdcfbb4bed7cdf756767769597ad978c423ee0ba4b040c2",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["Ship at faction headquarters", "Contract capacity"],
      consequences: ["creates an offered Contract"],
      success_evidence: ["Contract response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Contract state", "Agent credits"]},
      visibility: :agent_private,
      pagination: :none
    },
    %Operation{
      id: "orbit-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/orbit",
      spec_fingerprint: "478378d271740aeb12c843af3bec9c276247fc11e6d4ee9765853fc9e0dc2add",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["docked Ship"],
      consequences: ["changes Ship posture to orbit"],
      success_evidence: ["Ship nav response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "patch-ship-nav",
      method: :patch,
      path: "/my/ships/{shipSymbol}/nav",
      spec_fingerprint: "da1cb8bb720343cc158104554fac1812cb22c2bb957e59f9e017d75590a98285",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["eligible Ship flight mode"],
      consequences: ["changes Flight Mode"],
      success_evidence: ["Ship nav, fuel, and events response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "purchase-cargo",
      method: :post,
      path: "/my/ships/{shipSymbol}/purchase",
      spec_fingerprint: "b8fc5c959495db7df395f756c890d7d606ba254c178e490a72fb850aedd37fec",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship docked at selling Market", "Cargo capacity", "sufficient credits"],
      consequences: ["adds Cargo and spends credits"],
      success_evidence: ["Agent, Cargo, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Agent credits"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "purchase-ship",
      method: :post,
      path: "/my/ships",
      spec_fingerprint: "a92bed457b91b6bde77aa83a83e4ec2e78b7aea5cbb18ff1234405ab1efa6e32",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["Shipyard offer", "sufficient unreserved credits"],
      consequences: ["spends credits and adds a Ship"],
      success_evidence: ["Agent, Ship, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["owned Fleet", "Agent credits"]},
      visibility: :agent_private,
      pagination: :none
    },
    %Operation{
      id: "refuel-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/refuel",
      spec_fingerprint: "a2fb9da05d0d1ed4277656cf9e3a32376dca9b54e1a9430e39b81c842bacb94d",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship at refueling Waypoint", "sufficient credits or fuel Cargo"],
      consequences: ["adds Ship fuel and may spend credits or Cargo"],
      success_evidence: ["Agent, Cargo, fuel, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Agent credits"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "register",
      method: :post,
      path: "/register",
      spec_fingerprint: "1e74abd72c13dd3df7d39f62b21938389aa703114a3fe9b5f6a0537368eaf9e9",
      classification: :mutation,
      owner: :fleet_generation,
      prerequisites: ["AccountToken authority", "available Agent symbol"],
      consequences: ["mints an Agent and its initial Fleet"],
      success_evidence: ["registration response and AgentToken"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Agent existence by symbol"]},
      visibility: :agent_private,
      pagination: :none
    },
    %Operation{
      id: "remove-mount",
      method: :post,
      path: "/my/ships/{shipSymbol}/mounts/remove",
      spec_fingerprint: "b7efebf82ece903ef77d1be3db0cb010abbe4f94acc0beddadf5e04ebd7832a1",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship at capable Shipyard", "installed mount", "Cargo capacity"],
      consequences: ["moves mount from Ship into Cargo and may spend credits"],
      success_evidence: ["mounts, Cargo, Agent, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship Cargo", "Ship Readiness"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "remove-ship-module",
      method: :post,
      path: "/my/ships/{shipSymbol}/modules/remove",
      spec_fingerprint: "f185fbe52b7ff90a3516daab17e9fe8bd3da623518f82014163120186a1f3e89",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship docked at capable Shipyard", "installed module", "Cargo capacity"],
      consequences: ["moves module from Ship into Cargo and may spend credits"],
      success_evidence: ["modules, Cargo, Agent, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Ship Readiness"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "repair-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/repair",
      spec_fingerprint: "57da9e19ee1abedb7a2aececa72a288d0c39fc0bb5295dcc62256c9caafb1be1",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: [
        "Ship docked at capable Shipyard",
        "confirmed repair cost",
        "sufficient credits"
      ],
      consequences: ["restores Ship component condition and spends credits"],
      success_evidence: ["repaired Ship and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Ship Readiness"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "scrap-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/scrap",
      spec_fingerprint: "45d6d844385d3db2bf8dcddd91f0a61a1e3674b7b797d2b75a2d512a80314843",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["Ship docked at capable Shipyard", "confirmed scrap valuation"],
      consequences: ["removes Ship and adds credits"],
      success_evidence: ["Agent and scrap transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["owned Fleet", "Agent credits"]},
      visibility: :agent_private,
      pagination: :none
    },
    %Operation{
      id: "sell-cargo",
      method: :post,
      path: "/my/ships/{shipSymbol}/sell",
      spec_fingerprint: "def72dbb5778d7c23f89d4554b7770678489dc31106fbc78e6b6d8de92bbf14a",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship docked at buying Market", "Cargo units aboard"],
      consequences: ["removes Cargo and adds credits"],
      success_evidence: ["Agent, Cargo, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Agent credits"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "ship-refine",
      method: :post,
      path: "/my/ships/{shipSymbol}/refine",
      spec_fingerprint: "7b405cb19c80a45b423226f29d0c828da41ca67b445d78ac41c0d836d4c009aa",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["refinery module", "required Cargo"],
      consequences: ["converts Cargo"],
      success_evidence: ["Cargo, Cooldown, and production response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "siphon-resources",
      method: :post,
      path: "/my/ships/{shipSymbol}/siphon",
      spec_fingerprint: "c6fdd932b1113154466f5e36df29c37718ea9f86d950bb393284e6390232a6cb",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["siphon mount", "gas Waypoint", "Cargo capacity"],
      consequences: ["adds siphoned Cargo"],
      success_evidence: ["Siphon, Cargo, and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "supply-construction",
      method: :post,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/construction/supply",
      spec_fingerprint: "71c6984572025aee79be59a33320b0759b6e39c6e381a046b48c9c5513c9d463",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship present with required Cargo", "incomplete Construction"],
      consequences: ["removes Cargo and advances Construction"],
      success_evidence: ["Cargo and Construction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Construction state", "Ship Cargo"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "transfer-cargo",
      method: :post,
      path: "/my/ships/{shipSymbol}/transfer",
      spec_fingerprint: "4a0edc87b22ea10c3c5a1632617316620c3cb1ff802d1cdd151da58efb261a85",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["co-located Ships", "source Cargo", "target Cargo capacity"],
      consequences: ["moves Cargo between Ships"],
      success_evidence: ["source Cargo response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship Cargo", "Ship Readiness"]},
      visibility: :ship_private,
      pagination: :none
    },
    %Operation{
      id: "warp-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/warp",
      spec_fingerprint: "8026ac879f1dc9f823916d32bf4f690d22f9ba68587b25e9d96836434ec48454",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["warp capability", "reachable destination", "sufficient fuel"],
      consequences: ["starts inter-System transit"],
      success_evidence: ["Ship nav and fuel response"],
      waits: [:transit],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_private,
      pagination: :none
    }
  ]

  @spec all() :: [Operation.t()]
  def all, do: @operations

  @spec fetch!(String.t()) :: Operation.t()
  def fetch!(operation_id) do
    Enum.find(@operations, &(&1.id == operation_id)) ||
      raise KeyError, key: operation_id, term: __MODULE__
  end
end
