defmodule SpaceTraders.API.OperationInventory.Operation do
  @moduledoc false
  @enforce_keys [
    :id,
    :method,
    :path,
    :classification,
    :owner,
    :prerequisites,
    :consequences,
    :success_evidence,
    :waits,
    :ambiguity,
    :visibility,
    :pagination
  ]
  defstruct @enforce_keys

  @type t() :: %__MODULE__{}
end

defmodule SpaceTraders.API.OperationInventory do
  @moduledoc """
  Generated inventory of every operation in the pinned SpaceTraders API.

  Regenerate with `mix space_traders.gen.operations`; edit operation governance
  metadata in that task rather than editing this file directly.
  """

  alias SpaceTraders.API.OperationInventory.Operation

  @operations [
    %Operation{
      id: "accept-contract",
      method: :post,
      path: "/my/contracts/{contractId}/accept",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["available Contract before acceptance deadline"],
      consequences: ["accepts Contract and may pay acceptance credits"],
      success_evidence: ["Agent and Contract response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Contract state", "Agent credits"]},
      visibility: :agent,
      pagination: :none
    },
    %Operation{
      id: "create-chart",
      method: :post,
      path: "/my/ships/{shipSymbol}/chart",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["uncharted current Waypoint"],
      consequences: ["charts current Waypoint"],
      success_evidence: ["Chart and Waypoint response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "create-ship-ship-scan",
      method: :post,
      path: "/my/ships/{shipSymbol}/scan/ships",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["sensor mount", "eligible Ship"],
      consequences: ["observes nearby Ships"],
      success_evidence: ["scanned Ships and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "create-ship-system-scan",
      method: :post,
      path: "/my/ships/{shipSymbol}/scan/systems",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["sensor mount", "eligible Ship"],
      consequences: ["observes nearby Systems"],
      success_evidence: ["scanned Systems and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "create-ship-waypoint-scan",
      method: :post,
      path: "/my/ships/{shipSymbol}/scan/waypoints",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["sensor mount", "eligible Ship"],
      consequences: ["observes nearby Waypoints"],
      success_evidence: ["scanned Waypoints and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "create-survey",
      method: :post,
      path: "/my/ships/{shipSymbol}/survey",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["survey mount", "surveyable Waypoint"],
      consequences: ["creates Surveys"],
      success_evidence: ["Surveys and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "deliver-contract",
      method: :post,
      path: "/my/contracts/{contractId}/deliver",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship at delivery Waypoint with required Cargo"],
      consequences: ["removes Cargo and advances Contract delivery"],
      success_evidence: ["Cargo and Contract response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Contract delivery", "Ship Cargo"]},
      visibility: :agent,
      pagination: :none
    },
    %Operation{
      id: "dock-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/dock",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["orbiting Ship"],
      consequences: ["changes Ship posture to docked"],
      success_evidence: ["Ship nav response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "extract-resources",
      method: :post,
      path: "/my/ships/{shipSymbol}/extract",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["extraction mount", "extractable Waypoint", "Cargo capacity"],
      consequences: ["adds extracted Cargo"],
      success_evidence: ["Extraction, Cargo, and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "extract-resources-with-survey",
      method: :post,
      path: "/my/ships/{shipSymbol}/extract/survey",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["valid matching Survey", "extraction capability", "Cargo capacity"],
      consequences: ["adds extracted Cargo and may exhaust Survey"],
      success_evidence: ["Extraction, Cargo, events, and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "fulfill-contract",
      method: :post,
      path: "/my/contracts/{contractId}/fulfill",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["accepted Contract with all deliveries complete"],
      consequences: ["fulfills Contract and pays completion credits"],
      success_evidence: ["Agent and Contract response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Contract state", "Agent credits"]},
      visibility: :agent,
      pagination: :none
    },
    %Operation{
      id: "get-agent",
      method: :get,
      path: "/agents/{agentSymbol}",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "get-agents",
      method: :get,
      path: "/agents",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :page_limit
    },
    %Operation{
      id: "get-construction",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/construction",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "get-contract",
      method: :get,
      path: "/my/contracts/{contractId}",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :agent,
      pagination: :none
    },
    %Operation{
      id: "get-contracts",
      method: :get,
      path: "/my/contracts",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :agent,
      pagination: :page_limit
    },
    %Operation{
      id: "get-faction",
      method: :get,
      path: "/factions/{factionSymbol}",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "get-factions",
      method: :get,
      path: "/factions",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :page_limit
    },
    %Operation{
      id: "get-jump-gate",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/jump-gate",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "get-market",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/market",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :location_dependent,
      pagination: :none
    },
    %Operation{
      id: "get-mounts",
      method: :get,
      path: "/my/ships/{shipSymbol}/mounts",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "get-my-agent",
      method: :get,
      path: "/my/agent",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :agent,
      pagination: :none
    },
    %Operation{
      id: "get-my-ship",
      method: :get,
      path: "/my/ships/{shipSymbol}",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "get-my-ship-cargo",
      method: :get,
      path: "/my/ships/{shipSymbol}/cargo",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "get-my-ships",
      method: :get,
      path: "/my/ships",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :agent,
      pagination: :page_limit
    },
    %Operation{
      id: "get-repair-ship",
      method: :get,
      path: "/my/ships/{shipSymbol}/repair",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "get-scrap-ship",
      method: :get,
      path: "/my/ships/{shipSymbol}/scrap",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "get-ship-cooldown",
      method: :get,
      path: "/my/ships/{shipSymbol}/cooldown",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "get-ship-modules",
      method: :get,
      path: "/my/ships/{shipSymbol}/modules",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "get-ship-nav",
      method: :get,
      path: "/my/ships/{shipSymbol}/nav",
      classification: :read,
      owner: :evidence,
      prerequisites: ["AgentToken credential reference", "requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "get-shipyard",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/shipyard",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :location_dependent,
      pagination: :none
    },
    %Operation{
      id: "get-status",
      method: :get,
      path: "/",
      classification: :read,
      owner: :evidence,
      prerequisites: ["public API availability"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "get-supply-chain",
      method: :get,
      path: "/market/supply-chain",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "get-system",
      method: :get,
      path: "/systems/{systemSymbol}",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "get-system-waypoints",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :page_limit
    },
    %Operation{
      id: "get-systems",
      method: :get,
      path: "/systems",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :page_limit
    },
    %Operation{
      id: "get-waypoint",
      method: :get,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}",
      classification: :read,
      owner: :evidence,
      prerequisites: ["requested entity identifiers"],
      consequences: ["records an authoritative observation without changing game state"],
      success_evidence: ["successful response body with observation provenance"],
      waits: [],
      ambiguity: :safe_retry,
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "install-mount",
      method: :post,
      path: "/my/ships/{shipSymbol}/mounts/install",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship at capable Shipyard", "mount in Cargo", "Ship capacity"],
      consequences: ["moves mount from Cargo onto Ship and may spend credits"],
      success_evidence: ["mounts, Cargo, Agent, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship Cargo", "Ship Readiness"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "install-ship-module",
      method: :post,
      path: "/my/ships/{shipSymbol}/modules/install",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship docked at capable Shipyard", "module in Cargo", "Ship capacity"],
      consequences: ["moves module from Cargo onto Ship and may spend credits"],
      success_evidence: ["modules, Cargo, Agent, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Ship Readiness"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "jettison",
      method: :post,
      path: "/my/ships/{shipSymbol}/jettison",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Cargo units aboard"],
      consequences: ["removes Cargo"],
      success_evidence: ["Cargo response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship Cargo", "Ship Readiness"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "jump-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/jump",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["connected Jump Gate", "eligible Ship"],
      consequences: ["starts inter-System transit"],
      success_evidence: ["Ship nav, Agent, and Cooldown response"],
      waits: [:transit, :cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "navigate-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/navigate",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["reachable destination", "sufficient fuel"],
      consequences: ["starts local transit"],
      success_evidence: ["Ship nav and fuel response"],
      waits: [:transit],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "negotiateContract",
      method: :post,
      path: "/my/ships/{shipSymbol}/negotiate/contract",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["Ship at faction headquarters", "Contract capacity"],
      consequences: ["creates an offered Contract"],
      success_evidence: ["Contract response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Contract state", "Agent credits"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "orbit-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/orbit",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["docked Ship"],
      consequences: ["changes Ship posture to orbit"],
      success_evidence: ["Ship nav response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "patch-ship-nav",
      method: :patch,
      path: "/my/ships/{shipSymbol}/nav",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["eligible Ship flight mode"],
      consequences: ["changes Flight Mode"],
      success_evidence: ["Ship nav, fuel, and events response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "purchase-cargo",
      method: :post,
      path: "/my/ships/{shipSymbol}/purchase",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship docked at selling Market", "Cargo capacity", "sufficient credits"],
      consequences: ["adds Cargo and spends credits"],
      success_evidence: ["Agent, Cargo, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Agent credits"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "purchase-ship",
      method: :post,
      path: "/my/ships",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["Shipyard offer", "sufficient unreserved credits"],
      consequences: ["spends credits and adds a Ship"],
      success_evidence: ["Agent, Ship, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["owned Fleet", "Agent credits"]},
      visibility: :agent,
      pagination: :none
    },
    %Operation{
      id: "refuel-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/refuel",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship at refueling Waypoint", "sufficient credits or fuel Cargo"],
      consequences: ["adds Ship fuel and may spend credits or Cargo"],
      success_evidence: ["Agent, Cargo, fuel, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Agent credits"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "register",
      method: :post,
      path: "/register",
      classification: :mutation,
      owner: :fleet_generation,
      prerequisites: ["AccountToken authority", "available Agent symbol"],
      consequences: ["mints an Agent and its initial Fleet"],
      success_evidence: ["registration response and AgentToken"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Agent existence by symbol"]},
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "remove-mount",
      method: :post,
      path: "/my/ships/{shipSymbol}/mounts/remove",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship at capable Shipyard", "installed mount", "Cargo capacity"],
      consequences: ["moves mount from Ship into Cargo and may spend credits"],
      success_evidence: ["mounts, Cargo, Agent, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship Cargo", "Ship Readiness"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "remove-ship-module",
      method: :post,
      path: "/my/ships/{shipSymbol}/modules/remove",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship docked at capable Shipyard", "installed module", "Cargo capacity"],
      consequences: ["moves module from Ship into Cargo and may spend credits"],
      success_evidence: ["modules, Cargo, Agent, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Ship Readiness"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "repair-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/repair",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: [
        "Ship docked at capable Shipyard",
        "confirmed repair cost",
        "sufficient credits"
      ],
      consequences: ["restores Ship component condition and spends credits"],
      success_evidence: ["repaired Ship and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Ship Readiness"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "scrap-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/scrap",
      classification: :mutation,
      owner: :fleet_reconciliation,
      prerequisites: ["Ship docked at capable Shipyard", "confirmed scrap valuation"],
      consequences: ["removes Ship and adds credits"],
      success_evidence: ["Agent and scrap transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["owned Fleet", "Agent credits"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "sell-cargo",
      method: :post,
      path: "/my/ships/{shipSymbol}/sell",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship docked at buying Market", "Cargo units aboard"],
      consequences: ["removes Cargo and adds credits"],
      success_evidence: ["Agent, Cargo, and transaction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship state", "Agent credits"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "ship-refine",
      method: :post,
      path: "/my/ships/{shipSymbol}/refine",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["refinery module", "required Cargo"],
      consequences: ["converts Cargo"],
      success_evidence: ["Cargo, Cooldown, and production response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "siphon-resources",
      method: :post,
      path: "/my/ships/{shipSymbol}/siphon",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["siphon mount", "gas Waypoint", "Cargo capacity"],
      consequences: ["adds siphoned Cargo"],
      success_evidence: ["Siphon, Cargo, and Cooldown response"],
      waits: [:cooldown],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "supply-construction",
      method: :post,
      path: "/systems/{systemSymbol}/waypoints/{waypointSymbol}/construction/supply",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["Ship present with required Cargo", "incomplete Construction"],
      consequences: ["removes Cargo and advances Construction"],
      success_evidence: ["Cargo and Construction response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Construction state", "Ship Cargo"]},
      visibility: :public,
      pagination: :none
    },
    %Operation{
      id: "transfer-cargo",
      method: :post,
      path: "/my/ships/{shipSymbol}/transfer",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["co-located Ships", "source Cargo", "target Cargo capacity"],
      consequences: ["moves Cargo between Ships"],
      success_evidence: ["source Cargo response"],
      waits: [],
      ambiguity: {:reconcile_before_retry, ["Ship Cargo", "Ship Readiness"]},
      visibility: :ship_local,
      pagination: :none
    },
    %Operation{
      id: "warp-ship",
      method: :post,
      path: "/my/ships/{shipSymbol}/warp",
      classification: :mutation,
      owner: :ship_execution,
      prerequisites: ["warp capability", "reachable destination", "sufficient fuel"],
      consequences: ["starts inter-System transit"],
      success_evidence: ["Ship nav and fuel response"],
      waits: [:transit],
      ambiguity: {:reconcile_before_retry, ["Ship state"]},
      visibility: :ship_local,
      pagination: :none
    }
  ]

  @spec all() :: [Operation.t()]
  def all, do: @operations

  @spec fetch!(String.t()) :: Operation.t()
  def fetch!(operation_id) do
    Enum.find(@operations, &(&1.id == operation_id)) ||
      raise KeyError, key: operation_id, term: __MODULE__
  end
end
